name: tp1
services:
  rabbitmq:
    container_name: rabbit
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672/" ]
      interval: 10s
      timeout: 5s
      retries: 10

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
      - gateway
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - BOOKS_PATH=/data/books_data.csv
      - BOOKS_REVIEWS_PATH=/data/Books_rating.csv
    volumes:
      - ./data:/data

  # category_filter:
  #   container_name: category_filter
  #   image: book-filter:latest
  #   entrypoint: python3 /main.py
  #   depends_on:
  #     - rabbitmq
  #   links:
  #     - rabbitmq
  #   environment:
  #     - ID=1
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=DEBUG
  #     - CATEGORY=Computers
  #     - OUTPUT_QUEUE=computers_filtered
  #     - EXCHANGE=query


  # published_year_filter:
  #   container_name: published_year_filter
  #   image: book-filter:latest
  #   entrypoint: python3 /main.py
  #   environment:
  #     - ID=2
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=DEBUG
  #     - PUBLISHED_YEAR_RANGE=2000-2023
  #     - INPUT_QUEUE=computers_filtered
  #     - OUTPUT_QUEUE=published_year_filtered

  # title_contains_filter:
  #   container_name: title_contains_filter
  #   image: book-filter:latest
  #   entrypoint: python3 /main.py
  #   depends_on:
  #     - rabbitmq
  #   links:
  #     - rabbitmq
  #   environment:
  #     - ID=3
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=DEBUG
  #     - TITLE_CONTAINS=distributed
  #     - INPUT_QUEUE=published_year_filtered
  #     - OUTPUT_QUEUE=result

  decades_accumulator:
    container_name: decades_accumulator
    image: decades_accumulator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - TOP=10
      - EXCHANGE=query
      - OUTPUT_QUEUE=result

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /main.py
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - EXCHANGE=query
    # reviews_counter:
    #   container_name: reviews_counter
    #   image: reviews_counter_accum:latest
    #   entrypoint: python3 /main.py
    #   environment:
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=INFO
    #     - TOP=10
    #   networks:
    #     - testing_net


    # title_contains_filter:
    #   container_name: title_contains_filter
    #   image: book-filter:latest
    #   entrypoint: python3 /main.py
    #   environment:
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=INFO
    #     - TITLE_CONTAINS=distributed
    #   networks:
    #     - testing_net

