name: tp1
services:
  # rabbitmq:
  #   build:
  #     context: ./rabbitmq
  #     dockerfile: rabbitmq.dockerfile
  #   ports:
  #     - 15672:15672

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
      - gateway
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - BOOKS_PATH=/data/books_data.csv
      - BOOKS_REVIEWS_PATH=/data/Books_rating.csv
    volumes:
      - ./data:/data
    networks:
      - testing_net
  # category_filter:
  #   container_name: category_filter
  #   image: book-filter:latest
  #   entrypoint: python3 /main.py
  #   depends_on:
  #     - rabbitmq
  #   links:
  #     - rabbitmq
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=DEBUG
  #     - CATEGORY=Computers

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /main.py
    # depends_on:
    #   - rabbitmq
    # links:
    #   - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
  # decades_accumulator:
  #   container_name: decades_accumulator
  #   image: decades_accumulator:latest
  #   entrypoint: python3 /main.py
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=DEBUG
  #   networks:
  #     - testing_net

  # reviews_counter:
  #   container_name: reviews_counter
  #   image: reviews_counter_accum:latest
  #   entrypoint: python3 /main.py
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=DEBUG
  #     - TOP=10
  #   networks:
  #     - testing_net


  # published_year_filter:
  #   container_name: published_year_filter
  #   image: book-filter:latest
  #   entrypoint: python3 /main.py
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=DEBUG
  #     - PUBLISHED_YEAR_RANGE=2000-2023
  #   networks:
  #     - testing_net

  # title_contains_filter:
  #   container_name: title_contains_filter
  #   image: book-filter:latest
  #   entrypoint: python3 /main.py
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=DEBUG
  #     - TITLE_CONTAINS=distributed
  #   networks:
  #     - testing_net
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
