name: tp1
services:
  sender_client_0:
    container_name: sender_client_0
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
      - gateway
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - BOOKS_PATH=/data/books_data.csv
      - BOOKS_REVIEWS_PATH=/data/Books_rating.csv
    volumes:
      - ./data/csv:/data
      - ./data/query:/query
  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - OUTPUT_QUEUES=query1:3;query2:3;query3:3;query4:3
      - INPUT_QUEUE=results
      - QUERY_COUNT=11
      - ID=0
  computers_category_filter_0:
    container_name: computers_category_filter_0
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query1
      - OUTPUT_QUEUES=computers:3
      - CATEGORY=Computers
      - ID=0
      - IS_EQUAL=True
    volumes:
      - ./data/checkpoint/computers_category_filter_0:/.checkpoints
  computers_category_filter_1:
    container_name: computers_category_filter_1
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query1
      - OUTPUT_QUEUES=computers:3
      - CATEGORY=Computers
      - ID=1
      - IS_EQUAL=True
    volumes:
      - ./data/checkpoint/computers_category_filter_1:/.checkpoints
  computers_category_filter_2:
    container_name: computers_category_filter_2
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query1
      - OUTPUT_QUEUES=computers:3
      - CATEGORY=Computers
      - ID=2
      - IS_EQUAL=True
    volumes:
      - ./data/checkpoint/computers_category_filter_2:/.checkpoints
  2000s_published_year_filter_0:
    container_name: 2000s_published_year_filter_0
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=computers
      - OUTPUT_QUEUES=2000s_filtered:3
      - PUBLISHED_YEAR_RANGE=2000-2023
      - ID=0
      - PREVIOUS_WORKERS=3
    volumes:
      - ./data/checkpoint/2000s_published_year_filter_0:/.checkpoints
  2000s_published_year_filter_1:
    container_name: 2000s_published_year_filter_1
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=computers
      - OUTPUT_QUEUES=2000s_filtered:3
      - PUBLISHED_YEAR_RANGE=2000-2023
      - ID=1
      - PREVIOUS_WORKERS=3
    volumes:
      - ./data/checkpoint/2000s_published_year_filter_1:/.checkpoints
  2000s_published_year_filter_2:
    container_name: 2000s_published_year_filter_2
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=computers
      - OUTPUT_QUEUES=2000s_filtered:3
      - PUBLISHED_YEAR_RANGE=2000-2023
      - ID=2
      - PREVIOUS_WORKERS=3
    volumes:
      - ./data/checkpoint/2000s_published_year_filter_2:/.checkpoints
  title_contains_filter_0:
    container_name: title_contains_filter_0
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=2000s_filtered
      - OUTPUT_QUEUES=results:1
      - TITLE_CONTAINS=distributed
      - ID=0
      - QUERY=1
      - PREVIOUS_WORKERS=3
    volumes:
      - ./data/checkpoint/title_contains_filter_0:/.checkpoints
  title_contains_filter_1:
    container_name: title_contains_filter_1
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=2000s_filtered
      - OUTPUT_QUEUES=results:1
      - TITLE_CONTAINS=distributed
      - ID=1
      - QUERY=1
      - PREVIOUS_WORKERS=3
    volumes:
      - ./data/checkpoint/title_contains_filter_1:/.checkpoints
  title_contains_filter_2:
    container_name: title_contains_filter_2
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=2000s_filtered
      - OUTPUT_QUEUES=results:1
      - TITLE_CONTAINS=distributed
      - ID=2
      - QUERY=1
      - PREVIOUS_WORKERS=3
    volumes:
      - ./data/checkpoint/title_contains_filter_2:/.checkpoints
