name: tp1
services:
  sender_client_0:
    container_name: sender_client_0
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
    - gateway
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - BOOKS_PATH=/data/books_data_reduced.csv
    - BOOKS_REVIEWS_PATH=/data/Books_rating_reduced.csv
    volumes:
    - ./data/csv:/data
    - ./data/0/query:/query
  sender_client_1:
    container_name: sender_client_1
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
    - gateway
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - BOOKS_PATH=/data/books_data_reduced.csv
    - BOOKS_REVIEWS_PATH=/data/Books_rating_reduced.csv
    volumes:
    - ./data/csv:/data
    - ./data/1/query:/query
  sender_client_2:
    container_name: sender_client_2
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
    - gateway
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - BOOKS_PATH=/data/books_data_reduced.csv
    - BOOKS_REVIEWS_PATH=/data/Books_rating_reduced.csv
    volumes:
    - ./data/csv:/data
    - ./data/2/query:/query
  monitor0:
    container_name: monitor0
    image: monitor:latest
    privileged: true
    entrypoint: python3 /main.py
    environment:
    - ID=0
    - NAME=monitor0
    - WORKERS=computers_category_filter_0,computers_category_filter_1,computers_category_filter_2,computers_category_filter_3,2000s_published_year_filter_0,2000s_published_year_filter_1,2000s_published_year_filter_2,2000s_published_year_filter_3,title_contains_filter_0,title_contains_filter_1,title_contains_filter_2,title_contains_filter_3,decades_accumulator_0,decades_accumulator_1,decades_accumulator_2,decades_accumulator_3,1990s_published_year_filter_0,1990s_published_year_filter_1,1990s_published_year_filter_2,1990s_published_year_filter_3,reviews_counter_0,reviews_counter_1,reviews_counter_2,reviews_counter_3,fiction_category_filter_0,fiction_category_filter_1,fiction_category_filter_2,fiction_category_filter_3,sentiment_analyzer_0,sentiment_analyzer_1,sentiment_analyzer_2,sentiment_analyzer_3,avg_rating_accumulator,sentiment_score_accumulator gateway
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  monitor1:
    container_name: monitor1
    image: monitor:latest
    privileged: true
    entrypoint: python3 /main.py
    environment:
    - ID=1
    - NAME=monitor1
    - WORKERS=computers_category_filter_0,computers_category_filter_1,computers_category_filter_2,computers_category_filter_3,2000s_published_year_filter_0,2000s_published_year_filter_1,2000s_published_year_filter_2,2000s_published_year_filter_3,title_contains_filter_0,title_contains_filter_1,title_contains_filter_2,title_contains_filter_3,decades_accumulator_0,decades_accumulator_1,decades_accumulator_2,decades_accumulator_3,1990s_published_year_filter_0,1990s_published_year_filter_1,1990s_published_year_filter_2,1990s_published_year_filter_3,reviews_counter_0,reviews_counter_1,reviews_counter_2,reviews_counter_3,fiction_category_filter_0,fiction_category_filter_1,fiction_category_filter_2,fiction_category_filter_3,sentiment_analyzer_0,sentiment_analyzer_1,sentiment_analyzer_2,sentiment_analyzer_3,avg_rating_accumulator,sentiment_score_accumulator gateway
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  monitor2:
    container_name: monitor2
    image: monitor:latest
    privileged: true
    entrypoint: python3 /main.py
    environment:
    - ID=2
    - NAME=monitor2
    - WORKERS=computers_category_filter_0,computers_category_filter_1,computers_category_filter_2,computers_category_filter_3,2000s_published_year_filter_0,2000s_published_year_filter_1,2000s_published_year_filter_2,2000s_published_year_filter_3,title_contains_filter_0,title_contains_filter_1,title_contains_filter_2,title_contains_filter_3,decades_accumulator_0,decades_accumulator_1,decades_accumulator_2,decades_accumulator_3,1990s_published_year_filter_0,1990s_published_year_filter_1,1990s_published_year_filter_2,1990s_published_year_filter_3,reviews_counter_0,reviews_counter_1,reviews_counter_2,reviews_counter_3,fiction_category_filter_0,fiction_category_filter_1,fiction_category_filter_2,fiction_category_filter_3,sentiment_analyzer_0,sentiment_analyzer_1,sentiment_analyzer_2,sentiment_analyzer_3,avg_rating_accumulator,sentiment_score_accumulator,gateway
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - OUTPUT_QUEUES=query1:4;query2:4;query3:4;query4:4
    - INPUT_QUEUE=results
    - QUERY_COUNT=14
    - ID=0
    - NAME=gateway
  computers_category_filter_0:
    container_name: computers_category_filter_0
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query1
    - OUTPUT_QUEUES=computers:4
    - CATEGORY=Computers
    - ID=0
    - IS_EQUAL=True
    - NAME=computers_category_filter_0
    volumes:
    - ./data/checkpoint/computers_category_filter_0:/.checkpoints
  computers_category_filter_1:
    container_name: computers_category_filter_1
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query1
    - OUTPUT_QUEUES=computers:4
    - CATEGORY=Computers
    - ID=1
    - IS_EQUAL=True
    - NAME=computers_category_filter_1
    volumes:
    - ./data/checkpoint/computers_category_filter_1:/.checkpoints
  computers_category_filter_2:
    container_name: computers_category_filter_2
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query1
    - OUTPUT_QUEUES=computers:4
    - CATEGORY=Computers
    - ID=2
    - IS_EQUAL=True
    - NAME=computers_category_filter_2
    volumes:
    - ./data/checkpoint/computers_category_filter_2:/.checkpoints
  computers_category_filter_3:
    container_name: computers_category_filter_3
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query1
    - OUTPUT_QUEUES=computers:4
    - CATEGORY=Computers
    - ID=3
    - IS_EQUAL=True
    - NAME=computers_category_filter_3
    volumes:
    - ./data/checkpoint/computers_category_filter_3:/.checkpoints
  2000s_published_year_filter_0:
    container_name: 2000s_published_year_filter_0
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=computers
    - OUTPUT_QUEUES=2000s_filtered:4
    - PUBLISHED_YEAR_RANGE=2000-2023
    - ID=0
    - PREVIOUS_WORKERS=4
    - NAME=2000s_published_year_filter_0
    volumes:
    - ./data/checkpoint/2000s_published_year_filter_0:/.checkpoints
  2000s_published_year_filter_1:
    container_name: 2000s_published_year_filter_1
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=computers
    - OUTPUT_QUEUES=2000s_filtered:4
    - PUBLISHED_YEAR_RANGE=2000-2023
    - ID=1
    - PREVIOUS_WORKERS=4
    - NAME=2000s_published_year_filter_1
    volumes:
    - ./data/checkpoint/2000s_published_year_filter_1:/.checkpoints
  2000s_published_year_filter_2:
    container_name: 2000s_published_year_filter_2
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=computers
    - OUTPUT_QUEUES=2000s_filtered:4
    - PUBLISHED_YEAR_RANGE=2000-2023
    - ID=2
    - PREVIOUS_WORKERS=4
    - NAME=2000s_published_year_filter_2
    volumes:
    - ./data/checkpoint/2000s_published_year_filter_2:/.checkpoints
  2000s_published_year_filter_3:
    container_name: 2000s_published_year_filter_3
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=computers
    - OUTPUT_QUEUES=2000s_filtered:4
    - PUBLISHED_YEAR_RANGE=2000-2023
    - ID=3
    - PREVIOUS_WORKERS=4
    - NAME=2000s_published_year_filter_3
    volumes:
    - ./data/checkpoint/2000s_published_year_filter_3:/.checkpoints
  title_contains_filter_0:
    container_name: title_contains_filter_0
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=2000s_filtered
    - OUTPUT_QUEUES=results:1
    - TITLE_CONTAINS=distributed
    - ID=0
    - QUERY=1
    - PREVIOUS_WORKERS=4
    - NAME=title_contains_filter_0
    volumes:
    - ./data/checkpoint/title_contains_filter_0:/.checkpoints
  title_contains_filter_1:
    container_name: title_contains_filter_1
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=2000s_filtered
    - OUTPUT_QUEUES=results:1
    - TITLE_CONTAINS=distributed
    - ID=1
    - QUERY=1
    - PREVIOUS_WORKERS=4
    - NAME=title_contains_filter_1
    volumes:
    - ./data/checkpoint/title_contains_filter_1:/.checkpoints
  title_contains_filter_2:
    container_name: title_contains_filter_2
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=2000s_filtered
    - OUTPUT_QUEUES=results:1
    - TITLE_CONTAINS=distributed
    - ID=2
    - QUERY=1
    - PREVIOUS_WORKERS=4
    - NAME=title_contains_filter_2
    volumes:
    - ./data/checkpoint/title_contains_filter_2:/.checkpoints
  title_contains_filter_3:
    container_name: title_contains_filter_3
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=2000s_filtered
    - OUTPUT_QUEUES=results:1
    - TITLE_CONTAINS=distributed
    - ID=3
    - QUERY=1
    - PREVIOUS_WORKERS=4
    - NAME=title_contains_filter_3
    volumes:
    - ./data/checkpoint/title_contains_filter_3:/.checkpoints
  decades_accumulator_0:
    container_name: decades_accumulator_0
    image: decades_accumulator:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query2
    - OUTPUT_QUEUES=results:1
    - TOP=10
    - ID=0
    - QUERY=2
    - NAME=decades_accumulator_0
    volumes:
    - ./data/checkpoint/decades_accumulator_0:/.checkpoints
  decades_accumulator_1:
    container_name: decades_accumulator_1
    image: decades_accumulator:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query2
    - OUTPUT_QUEUES=results:1
    - TOP=10
    - ID=1
    - QUERY=2
    - NAME=decades_accumulator_1
    volumes:
    - ./data/checkpoint/decades_accumulator_1:/.checkpoints
  decades_accumulator_2:
    container_name: decades_accumulator_2
    image: decades_accumulator:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query2
    - OUTPUT_QUEUES=results:1
    - TOP=10
    - ID=2
    - QUERY=2
    - NAME=decades_accumulator_2
    volumes:
    - ./data/checkpoint/decades_accumulator_2:/.checkpoints
  decades_accumulator_3:
    container_name: decades_accumulator_3
    image: decades_accumulator:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query2
    - OUTPUT_QUEUES=results:1
    - TOP=10
    - ID=3
    - QUERY=2
    - NAME=decades_accumulator_3
    volumes:
    - ./data/checkpoint/decades_accumulator_3:/.checkpoints
  1990s_published_year_filter_0:
    container_name: 1990s_published_year_filter_0
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query3
    - OUTPUT_QUEUES=90s_filtered:4
    - PUBLISHED_YEAR_RANGE=1990-1999
    - ID=0
    - SAVE_BOOKS=True
    - NAME=1990s_published_year_filter_0
    volumes:
    - ./data/checkpoint/1990s_published_year_filter_0:/.checkpoints
  1990s_published_year_filter_1:
    container_name: 1990s_published_year_filter_1
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query3
    - OUTPUT_QUEUES=90s_filtered:4
    - PUBLISHED_YEAR_RANGE=1990-1999
    - ID=1
    - SAVE_BOOKS=True
    - NAME=1990s_published_year_filter_1
    volumes:
    - ./data/checkpoint/1990s_published_year_filter_1:/.checkpoints
  1990s_published_year_filter_2:
    container_name: 1990s_published_year_filter_2
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query3
    - OUTPUT_QUEUES=90s_filtered:4
    - PUBLISHED_YEAR_RANGE=1990-1999
    - ID=2
    - SAVE_BOOKS=True
    - NAME=1990s_published_year_filter_2
    volumes:
    - ./data/checkpoint/1990s_published_year_filter_2:/.checkpoints
  1990s_published_year_filter_3:
    container_name: 1990s_published_year_filter_3
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query3
    - OUTPUT_QUEUES=90s_filtered:4
    - PUBLISHED_YEAR_RANGE=1990-1999
    - ID=3
    - SAVE_BOOKS=True
    - NAME=1990s_published_year_filter_3
    volumes:
    - ./data/checkpoint/1990s_published_year_filter_3:/.checkpoints
  reviews_counter_0:
    container_name: reviews_counter_0
    image: reviews_counter_accum:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=90s_filtered
    - OUTPUT_QUEUES=500_reviews:1;results:1
    - ID=0
    - QUERY=3
    - PREVIOUS_WORKERS=4
    - NAME=reviews_counter_0
    volumes:
    - ./data/checkpoint/reviews_counter_0:/.checkpoints
  reviews_counter_1:
    container_name: reviews_counter_1
    image: reviews_counter_accum:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=90s_filtered
    - OUTPUT_QUEUES=500_reviews:1;results:1
    - ID=1
    - QUERY=3
    - PREVIOUS_WORKERS=4
    - NAME=reviews_counter_1
    volumes:
    - ./data/checkpoint/reviews_counter_1:/.checkpoints
  reviews_counter_2:
    container_name: reviews_counter_2
    image: reviews_counter_accum:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=90s_filtered
    - OUTPUT_QUEUES=500_reviews:1;results:1
    - ID=2
    - QUERY=3
    - PREVIOUS_WORKERS=4
    - NAME=reviews_counter_2
    volumes:
    - ./data/checkpoint/reviews_counter_2:/.checkpoints
  reviews_counter_3:
    container_name: reviews_counter_3
    image: reviews_counter_accum:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=90s_filtered
    - OUTPUT_QUEUES=500_reviews:1;results:1
    - ID=3
    - QUERY=3
    - PREVIOUS_WORKERS=4
    - NAME=reviews_counter_3
    volumes:
    - ./data/checkpoint/reviews_counter_3:/.checkpoints
  avg_rating_accumulator:
    container_name: avg_rating_accumulator
    image: top_rating_accumulator:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=500_reviews
    - OUTPUT_QUEUES=results:1
    - ID=0
    - QUERY=4
    - PREVIOUS_WORKERS=4
    - NAME=avg_rating_accumulator
    volumes:
    - ./data/checkpoint/avg_rating_accumulator:/.checkpoints
  fiction_category_filter_0:
    container_name: fiction_category_filter_0
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query4
    - OUTPUT_QUEUES=fiction:4
    - CATEGORY=fiction
    - ID=0
    - SAVE_BOOKS=True
    - NO_SEND=True
    - NAME=fiction_category_filter_0
    volumes:
    - ./data/checkpoint/fiction_category_filter_0:/.checkpoints
  fiction_category_filter_1:
    container_name: fiction_category_filter_1
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query4
    - OUTPUT_QUEUES=fiction:4
    - CATEGORY=fiction
    - ID=1
    - SAVE_BOOKS=True
    - NO_SEND=True
    - NAME=fiction_category_filter_1
    volumes:
    - ./data/checkpoint/fiction_category_filter_1:/.checkpoints
  fiction_category_filter_2:
    container_name: fiction_category_filter_2
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query4
    - OUTPUT_QUEUES=fiction:4
    - CATEGORY=fiction
    - ID=2
    - SAVE_BOOKS=True
    - NO_SEND=True
    - NAME=fiction_category_filter_2
    volumes:
    - ./data/checkpoint/fiction_category_filter_2:/.checkpoints
  fiction_category_filter_3:
    container_name: fiction_category_filter_3
    image: book_filter:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=query4
    - OUTPUT_QUEUES=fiction:4
    - CATEGORY=fiction
    - ID=3
    - SAVE_BOOKS=True
    - NO_SEND=True
    - NAME=fiction_category_filter_3
    volumes:
    - ./data/checkpoint/fiction_category_filter_3:/.checkpoints
  sentiment_analyzer_0:
    container_name: sentiment_analyzer_0
    image: sentiment_analyzer:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=fiction
    - OUTPUT_QUEUES=sentiment_score:1
    - ID=0
    - PREVIOUS_WORKERS=4
    - NAME=sentiment_analyzer_0
    volumes:
    - ./data/checkpoint/sentiment_analyzer_0:/.checkpoints
  sentiment_analyzer_1:
    container_name: sentiment_analyzer_1
    image: sentiment_analyzer:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=fiction
    - OUTPUT_QUEUES=sentiment_score:1
    - ID=1
    - PREVIOUS_WORKERS=4
    - NAME=sentiment_analyzer_1
    volumes:
    - ./data/checkpoint/sentiment_analyzer_1:/.checkpoints
  sentiment_analyzer_2:
    container_name: sentiment_analyzer_2
    image: sentiment_analyzer:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=fiction
    - OUTPUT_QUEUES=sentiment_score:1
    - ID=2
    - PREVIOUS_WORKERS=4
    - NAME=sentiment_analyzer_2
    volumes:
    - ./data/checkpoint/sentiment_analyzer_2:/.checkpoints
  sentiment_analyzer_3:
    container_name: sentiment_analyzer_3
    image: sentiment_analyzer:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=fiction
    - OUTPUT_QUEUES=sentiment_score:1
    - ID=3
    - PREVIOUS_WORKERS=4
    - NAME=sentiment_analyzer_3
    volumes:
    - ./data/checkpoint/sentiment_analyzer_3:/.checkpoints
  sentiment_score_accumulator:
    container_name: sentiment_score_accumulator
    image: sentiment_score_accumulator:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    - INPUT_QUEUE=sentiment_score
    - OUTPUT_QUEUES=results:1
    - ID=0
    - QUERY=5
    - PREVIOUS_WORKERS=4
    - NAME=sentiment_score_accumulator
    volumes:
    - ./data/checkpoint/sentiment_score_accumulator:/.checkpoints
