name: tp1
services:
  rabbitmq:
    container_name: rabbit
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672/" ]
      interval: 10s
      timeout: 5s
      retries: 10

  ###########################################################################
  #----------------------------------GENERICOS-------------------------------
  ###########################################################################

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
      - gateway
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - BOOKS_PATH=/data/books_data.csv
      - BOOKS_REVIEWS_PATH=/data/Books_rating.csv
    volumes:
      - ./data:/data

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - OUTPUT_QUEUES=query1:3;query2:3;query3:3;query4:3
      - INPUT_QUEUE=results
      - QUERY_COUNT=1
      - ID=0

  ###########################################################################
  #------------------------------------QUERY 1-------------------------------
  ###########################################################################

  computers_category_filter_1:
    container_name: computers_category_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_QUEUE=query1
      - OUTPUT_QUEUES=computers:3
      - CATEGORY=Computers
      - ID=0

  computers_category_filter_2:
    container_name: computers_category_filter_2
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_QUEUE=query1
      - OUTPUT_QUEUES=computers:3
      - CATEGORY=Computers
      - ID=1

  computers_category_filter_3:
    container_name: computers_category_filter_3
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT_QUEUE=query1
      - OUTPUT_QUEUES=computers:3
      - CATEGORY=Computers
      - ID=2

  2000s_published_year_filter_1:
    container_name: 2000s_published_year_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - PUBLISHED_YEAR_RANGE=2000-2023
      - INPUT_QUEUE=computers
      - OUTPUT_QUEUES=2000s_filtered:3
      - ID=0

  2000s_published_year_filter_2:
    container_name: 2000s_published_year_filter_2
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - PUBLISHED_YEAR_RANGE=2000-2023
      - INPUT_QUEUE=computers
      - OUTPUT_QUEUES=2000s_filtered:3
      - ID=1

  2000s_published_year_filter_3:
    container_name: 2000s_published_year_filter_3
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - PUBLISHED_YEAR_RANGE=2000-2023
      - INPUT_QUEUE=computers
      - OUTPUT_QUEUES=2000s_filtered:3
      - ID=2

  title_contains_filter_1:
    container_name: title_contains_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - ID=0
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - TITLE_CONTAINS=distributed
      - INPUT_QUEUE=2000s_filtered
      - OUTPUT_QUEUES=results:1
      - QUERY=1

  title_contains_filter_2:
    container_name: title_contains_filter_2
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - ID=1
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - TITLE_CONTAINS=distributed
      - INPUT_QUEUE=2000s_filtered
      - OUTPUT_QUEUES=results:1
      - QUERY=1

  title_contains_filter_3:
    container_name: title_contains_filter_3
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - ID=2
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - TITLE_CONTAINS=distributed
      - INPUT_QUEUE=2000s_filtered
      - OUTPUT_QUEUES=results:1
      - QUERY=1
    ###########################################################################
    #------------------------------------QUERY 2-------------------------------
    ###########################################################################

    # decades-accumulator:
    #   container_name: decades-accumulator
    #   image: decades-accumulator:latest
    #   entrypoint: python3 /main.py
    #   depends_on:
    #     - rabbitmq
    #   links:
    #     - rabbitmq
    #   environment:
    #     - ID=0
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=DEBUG
    #     - TOP=10
    #     - INPUT_QUEUE=query2
    #     - OUTPUT_QUEUES=results:1
    #     - QUERY=2
    ###########################################################################
    #------------------------------QUERIES 3 Y 4-------------------------------
    ###########################################################################

    # 1990s_published_year_filter:
    #   container_name: 1990s_published_year_filter
    #   image: book-filter:latest
    #   entrypoint: python3 /main.py
    #   depends_on:
    #     - rabbitmq
    #   links:
    #     - rabbitmq
    #   environment:
    #     - ID=0
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=INFO
    #     - PUBLISHED_YEAR_RANGE=1990-1999
    #     - INPUT_QUEUE=query3
    #     - OUTPUT_QUEUES=90s_filtered:1
    #     - SAVE_BOOKS=True

    # reviews_counter:
    #   container_name: reviews_counter
    #   image: reviews_counter_accum:latest
    #   entrypoint: python3 /main.py
    #   depends_on:
    #     - rabbitmq
    #   links:
    #     - rabbitmq
    #   environment:
    #     - ID=5
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=INFO
    #     - INPUT_QUEUE=90s_filtered
    #     - OUTPUT_QUEUES=500_reviews,results
    #     - QUERY=3
    #     - N=1
    #QUERY 4
    # avg_rating_accumulator:
    #   container_name: avg_rating_accumulator
    #   image: accumulator:latest
    #   entrypoint: python3 /main.py
    #   depends_on:
    #     - rabbitmq
    #   links:
    #     - rabbitmq
    #   environment:
    #     - ID=6
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=INFO
    #     - INPUT_QUEUE=500_reviews
    #     - OUTPUT_QUEUES=results
    #     - QUERY=4
    ###########################################################################
    #------------------------------------QUERY 5-------------------------------
    ###########################################################################

    # fiction_category_filter_q5:
    #   container_name: fiction_category_filter_q5
    #   image: book-filter:latest
    #   entrypoint: python3 /main.py
    #   depends_on:
    #     - rabbitmq
    #   links:
    #     - rabbitmq
    #   environment:
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=DEBUG
    #     - EXCHANGE=query
    #     - OUTPUT_QUEUES=fiction_category_books_reviews
    #     - SAVE_BOOKS=True
    #     - CATEGORY=fiction
    #     - ID=7
    #     - N=1

    # sentiment_analyzer:
    #   container_name: sentiment_analyzer
    #   image: sentiment_analyzer:latest
    #   entrypoint: python3 /main.py
    #   depends_on:
    #     - rabbitmq
    #   links:
    #     - rabbitmq
    #   environment:
    #     - ID=8
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=INFO
    #     - INPUT_QUEUE=fiction_category_books_reviews
    #     - OUTPUT_QUEUES=sentiment_score
    #     - N=1

    # sentiment_score_accumulator:
    #   container_name: sentiment_score_accumulator
    #   image: sentiment_score_accumulator:latest
    #   entrypoint: python3 /main.py
    #   depends_on:
    #     - rabbitmq
    #   links:
    #     - rabbitmq
    #   environment:
    #     - ID=9
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=INFO
    #     - INPUT_QUEUE=sentiment_score
    #     - OUTPUT_QUEUES=results
    #     - QUERY=5
    ###########################################################################
    #                                 templates ???                           # 


    # category_filter:
    #   container_name: category_filter
    #   image: book-filter:latest
    #   entrypoint: python3 /main.py
    #   depends_on:
    #     - rabbitmq
    #   links:
    #     - rabbitmq
    #   environment:
    #     - ID=1
    #     - PYTHONUNBUFFERED=1
    #     - LOGGING_LEVEL=DEBUG
    #     - CATEGORY=Computers
    #     - OUTPUT_QUEUE=computers_filtered
    #     - EXCHANGE=query


    #sentiment_analyzer:
    # container_name: sentiment_analyzer
    # image: sentiment_analyzer:latest
    # entrypoint: python3 /main.py
    # depends_on:
    #   - rabbitmq
    # links:
    #   - rabbitmq
    # environment:
    #   - PYTHONUNBUFFERED=1
    #    - LOGGING_LEVEL=INFO
    #    - INPUT_QUEUE=fiction_category_books_reviews
    #    - OUTPUT_QUEUES=sentiment_score

