version: '3.9'
name: tp1
services:
  data_receiver:
    container_name: data_receiver
    image: data-receiver:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CATEGORY=Computers
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24