name: tp1
services:
  rabbitmq:
    container_name: rabbit
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672/" ]
      interval: 10s
      timeout: 5s
      retries: 10

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
      - gateway
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - BOOKS_PATH=/data/books_data.csv
      - BOOKS_REVIEWS_PATH=/data/Books_rating.csv
    volumes:
      - ./data:/data

  # decades-accumulator:
  #   container_name: decades-accumulator
  #   image: decades-accumulator:latest
  #   entrypoint: python3 /main.py
  #   environment:
  #     - ID=1
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=DEBUG
  #     - TOP=10
  #     - EXCHANGE=query
  #     - OUTPUT_QUEUE=result

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - EXCHANGE=query
      - INPUT_QUEUE=results

  computers_category_filter_1:
    container_name: computers_category_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - EXCHANGE=query
      - OUTPUT_QUEUES=results
      - CATEGORY=Computers
      - ID=0
      - N=1
      - QUERY=1
  fiction_category_filter_1:
    container_name: fiction_category_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - EXCHANGE=query
      - OUTPUT_QUEUES=fiction_category_books_reviews
      - SAVE_BOOKS=True
      - CATEGORY=fiction
      - ID=0
      - N=1

  sentiment_analyzer:
    container_name: sentiment_analyzer
    image: sentiment_analyzer:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=fiction_category_books_reviews
      - OUTPUT_QUEUES=sentiment_score

  sentiment_score_accumulator:
    container_name: sentiment_score_accumulator
    image: sentiment_score_accumulator:latest
    entrypoint: python3 /main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=sentiment_score
      - OUTPUT_QUEUES=results
      - QUERY=5
