version: '3.9'
name: tp1
services:
  reviews_counter:
    container_name: reviews_counter
    image: reviews_counter_accum:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - TOP=10
    networks:
      - testing_net
  
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
