name: tp1
services:
  sender_client:
    container_name: sender_client
    image: client:latest
    entrypoint: python3 /main.py
    depends_on:
      - gateway
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - BOOKS_PATH=/data/books_data.csv
      - BOOKS_REVIEWS_PATH=/data/Books_rating.csv
    volumes:
      - ./data:/data
      - ./query:/query
  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - OUTPUT_QUEUES=query1:3;query2:3;query3:3;query4:3
      - INPUT_QUEUE=results
      - QUERY_COUNT=11
      - ID=0

  computers_category_filter_0:
    container_name: computers_category_filter_0
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query1
      - OUTPUT_QUEUES=computers:3
      - CATEGORY=Computers
      - IS_EQUAL=True
      - ID=0

  computers_category_filter_1:
    container_name: computers_category_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query1
      - OUTPUT_QUEUES=computers:3
      - CATEGORY=Computers
      - IS_EQUAL=True
      - ID=1

  computers_category_filter_2:
    container_name: computers_category_filter_2
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query1
      - OUTPUT_QUEUES=computers:3
      - CATEGORY=Computers
      - IS_EQUAL=True
      - ID=2

  2000s_published_year_filter_0:
    container_name: 2000s_published_year_filter_0
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=computers
      - OUTPUT_QUEUES=2000s_filtered:3
      - PUBLISHED_YEAR_RANGE=2000-2023
      - ID=0
      - PREVIOUS_WORKERS=3

  2000s_published_year_filter_1:
    container_name: 2000s_published_year_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=computers
      - OUTPUT_QUEUES=2000s_filtered:3
      - PUBLISHED_YEAR_RANGE=2000-2023
      - ID=1
      - PREVIOUS_WORKERS=3

  2000s_published_year_filter_2:
    container_name: 2000s_published_year_filter_2
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=computers
      - OUTPUT_QUEUES=2000s_filtered:3
      - PUBLISHED_YEAR_RANGE=2000-2023
      - ID=2
      - PREVIOUS_WORKERS=3

  title_contains_filter_0:
    container_name: title_contains_filter_0
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=2000s_filtered
      - OUTPUT_QUEUES=results:1
      - TITLE_CONTAINS=distributed
      - ID=0
      - QUERY=1
      - PREVIOUS_WORKERS=3

  title_contains_filter_1:
    container_name: title_contains_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=2000s_filtered
      - OUTPUT_QUEUES=results:1
      - TITLE_CONTAINS=distributed
      - ID=1
      - QUERY=1
      - PREVIOUS_WORKERS=3

  title_contains_filter_2:
    container_name: title_contains_filter_2
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=2000s_filtered
      - OUTPUT_QUEUES=results:1
      - TITLE_CONTAINS=distributed
      - ID=2
      - QUERY=1
      - PREVIOUS_WORKERS=3

  decades-accumulator_0:
    container_name: decades-accumulator_0
    image: decades-accumulator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query2
      - OUTPUT_QUEUES=results:1
      - TOP=10
      - ID=0
      - QUERY=2

  decades-accumulator_1:
    container_name: decades-accumulator_1
    image: decades-accumulator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query2
      - OUTPUT_QUEUES=results:1
      - TOP=10
      - ID=1
      - QUERY=2

  decades-accumulator_2:
    container_name: decades-accumulator_2
    image: decades-accumulator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query2
      - OUTPUT_QUEUES=results:1
      - TOP=10
      - ID=2
      - QUERY=2

  1990s_published_year_filter_0:
    container_name: 1990s_published_year_filter_0
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query3
      - OUTPUT_QUEUES=90s_filtered:3
      - PUBLISHED_YEAR_RANGE=1990-1999
      - ID=0
      - SAVE_BOOKS=True

  1990s_published_year_filter_1:
    container_name: 1990s_published_year_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query3
      - OUTPUT_QUEUES=90s_filtered:3
      - PUBLISHED_YEAR_RANGE=1990-1999
      - ID=1
      - SAVE_BOOKS=True

  1990s_published_year_filter_2:
    container_name: 1990s_published_year_filter_2
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query3
      - OUTPUT_QUEUES=90s_filtered:3
      - PUBLISHED_YEAR_RANGE=1990-1999
      - ID=2
      - SAVE_BOOKS=True

  reviews_counter_0:
    container_name: reviews_counter_0
    image: reviews_counter_accum:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=90s_filtered
      - OUTPUT_QUEUES=500_reviews:1;results:1
      - ID=0
      - QUERY=3
      - PREVIOUS_WORKERS=3

  reviews_counter_1:
    container_name: reviews_counter_1
    image: reviews_counter_accum:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=90s_filtered
      - OUTPUT_QUEUES=500_reviews:1;results:1
      - ID=1
      - QUERY=3
      - PREVIOUS_WORKERS=3

  reviews_counter_2:
    container_name: reviews_counter_2
    image: reviews_counter_accum:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=90s_filtered
      - OUTPUT_QUEUES=500_reviews:1;results:1
      - ID=2
      - QUERY=3
      - PREVIOUS_WORKERS=3

  avg_rating_accumulator:
    container_name: avg_rating_accumulator
    image: accumulator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=500_reviews
      - OUTPUT_QUEUES=results:1
      - ID=0
      - QUERY=4
      - PREVIOUS_WORKERS=3

  fiction_category_filter_0:
    container_name: fiction_category_filter_0
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query4
      - OUTPUT_QUEUES=fiction:3
      - CATEGORY=Fiction
      - ID=0
      - SAVE_BOOKS=True

  fiction_category_filter_1:
    container_name: fiction_category_filter_1
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query4
      - OUTPUT_QUEUES=fiction:3
      - CATEGORY=Fiction
      - ID=1
      - SAVE_BOOKS=True

  fiction_category_filter_2:
    container_name: fiction_category_filter_2
    image: book-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=query4
      - OUTPUT_QUEUES=fiction:3
      - CATEGORY=Fiction
      - ID=2
      - SAVE_BOOKS=True

  sentiment_analyzer_0:
    container_name: sentiment_analyzer_0
    image: sentiment_analyzer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=fiction
      - OUTPUT_QUEUES=sentiment_score:1
      - ID=0
      - PREVIOUS_WORKERS=3

  sentiment_analyzer_1:
    container_name: sentiment_analyzer_1
    image: sentiment_analyzer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=fiction
      - OUTPUT_QUEUES=sentiment_score:1
      - ID=1
      - PREVIOUS_WORKERS=3

  sentiment_analyzer_2:
    container_name: sentiment_analyzer_2
    image: sentiment_analyzer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=fiction
      - OUTPUT_QUEUES=sentiment_score:1
      - ID=2
      - PREVIOUS_WORKERS=3

  sentiment_score_accumulator:
    container_name: sentiment_score_accumulator
    image: sentiment_score_accumulator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - INPUT_QUEUE=sentiment_score
      - OUTPUT_QUEUES=results:1
      - ID=0
      - QUERY=5
      - PREVIOUS_WORKERS=3
